//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolScoreBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoolScoreBuddy.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Score Buddy.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring has resumed - internet connectivity found..
        /// </summary>
        internal static string ConnectivityResumedMonitoringMessage {
            get {
                return ResourceManager.GetString("ConnectivityResumedMonitoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Copy and paste your unique tournament number below. .
        /// </summary>
        internal static string CopyPasteTournamentLabel {
            get {
                return ResourceManager.GetString("CopyPasteTournamentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error monitoring. Please manually check CueScore yourself..
        /// </summary>
        internal static string ErrorNotification {
            get {
                return ResourceManager.GetString("ErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Find the CueScore link for your tournament (usually shared with you by the organiser). 
        ///We want the number at the end. Around 8 digits. Here is an example of what to look for (do not use this one!).
        /// </summary>
        internal static string FindLinkLabel {
            get {
                return ResourceManager.GetString("FindLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a CueScore tournament and players to monitor. You&apos;ll be notified of match starts and scores..
        /// </summary>
        internal static string IntroductionLabel {
            get {
                return ResourceManager.GetString("IntroductionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must manually allow notifications for this app to work properly. Go to app settings, then permissions and under the &apos;not allowed&apos; list, modify the &apos;Notifications&apos; entry to become allowed..
        /// </summary>
        internal static string ManualNotificationsWarning {
            get {
                return ResourceManager.GetString("ManualNotificationsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitored.
        /// </summary>
        internal static string MonitoredButton {
            get {
                return ResourceManager.GetString("MonitoredButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup monitoring.
        /// </summary>
        internal static string MonitoringButton {
            get {
                return ResourceManager.GetString("MonitoringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring started..
        /// </summary>
        internal static string MonitoringStarted {
            get {
                return ResourceManager.GetString("MonitoringStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring stopped. No players or active tournaments to monitor..
        /// </summary>
        internal static string MonitoringStopped {
            get {
                return ResourceManager.GetString("MonitoringStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connectivity detected. Try again later..
        /// </summary>
        internal static string NoConnectivityMessage {
            get {
                return ResourceManager.GetString("NoConnectivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring has paused - no internet connectivity found..
        /// </summary>
        internal static string NoConnectivityMonitoringMessage {
            get {
                return ResourceManager.GetString("NoConnectivityMonitoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PlayersAPIServerExceptionButton {
            get {
                return ResourceManager.GetString("PlayersAPIServerExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string PlayersAPIServerExceptionMessage {
            get {
                return ResourceManager.GetString("PlayersAPIServerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch players {0}.
        /// </summary>
        internal static string PlayersAPIServerExceptionTitle {
            get {
                return ResourceManager.GetString("PlayersAPIServerExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PlayersGeneralExceptionButton {
            get {
                return ResourceManager.GetString("PlayersGeneralExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string PlayersGeneralExceptionMessage {
            get {
                return ResourceManager.GetString("PlayersGeneralExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch tournament {0}.
        /// </summary>
        internal static string PlayersGeneralExceptionTitle {
            get {
                return ResourceManager.GetString("PlayersGeneralExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PlayersHttpExceptionButton {
            get {
                return ResourceManager.GetString("PlayersHttpExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you have a data connection.
        /// </summary>
        internal static string PlayersHttpExceptionMessage {
            get {
                return ResourceManager.GetString("PlayersHttpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch players{0}.
        /// </summary>
        internal static string PlayersHttpExceptionTitle {
            get {
                return ResourceManager.GetString("PlayersHttpExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PlayersJsonExceptionButton {
            get {
                return ResourceManager.GetString("PlayersJsonExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider emailing me your tournament number ({0}) and this error message ({1}) at poolscorebuddy@outlook.com so I can look into fixing that. Thankyou..
        /// </summary>
        internal static string PlayersJsonExceptionMessage {
            get {
                return ResourceManager.GetString("PlayersJsonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing players{0}.
        /// </summary>
        internal static string PlayersJsonExceptionTitle {
            get {
                return ResourceManager.GetString("PlayersJsonExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of monitored players reached..
        /// </summary>
        internal static string PlayersMaximumReached {
            get {
                return ResourceManager.GetString("PlayersMaximumReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players available.
        /// </summary>
        internal static string PlayersNoneAvailable {
            get {
                return ResourceManager.GetString("PlayersNoneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Players.
        /// </summary>
        internal static string PlayersTitle {
            get {
                return ResourceManager.GetString("PlayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result {0}.
        /// </summary>
        internal static string ResultNotification {
            get {
                return ResourceManager.GetString("ResultNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} {1}.
        /// </summary>
        internal static string StartNotification {
            get {
                return ResourceManager.GetString("StartNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TournamentAPIServerExceptionButton {
            get {
                return ResourceManager.GetString("TournamentAPIServerExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TournamentAPIServerExceptionMessage {
            get {
                return ResourceManager.GetString("TournamentAPIServerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch tournament {0}.
        /// </summary>
        internal static string TournamentAPIServerExceptionTitle {
            get {
                return ResourceManager.GetString("TournamentAPIServerExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tournament number.
        /// </summary>
        internal static string TournamentEntryPlaceholder {
            get {
                return ResourceManager.GetString("TournamentEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has finished. Go back and choose another..
        /// </summary>
        internal static string TournamentFinishedLabel {
            get {
                return ResourceManager.GetString("TournamentFinishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TournamentGeneralExceptionButton {
            get {
                return ResourceManager.GetString("TournamentGeneralExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TournamentGeneralExceptionMessage {
            get {
                return ResourceManager.GetString("TournamentGeneralExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch tournament {0}.
        /// </summary>
        internal static string TournamentGeneralExceptionTitle {
            get {
                return ResourceManager.GetString("TournamentGeneralExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TournamentHttpExceptionButton {
            get {
                return ResourceManager.GetString("TournamentHttpExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you have a data connection.
        /// </summary>
        internal static string TournamentHttpExceptionMessage {
            get {
                return ResourceManager.GetString("TournamentHttpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch tournament {0}.
        /// </summary>
        internal static string TournamentHttpExceptionTitle {
            get {
                return ResourceManager.GetString("TournamentHttpExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check for app update. Cannot authenticate with server..
        /// </summary>
        internal static string TournamentHttpExceptionUnauthorisedMessage {
            get {
                return ResourceManager.GetString("TournamentHttpExceptionUnauthorisedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TournamentJsonExceptionButton {
            get {
                return ResourceManager.GetString("TournamentJsonExceptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider emailing me your tournament number ({0}) and this error message ({1}) at poolscorebuddy@outlook.com so I can look into fixing that. Thankyou..
        /// </summary>
        internal static string TournamentJsonExceptionMessage {
            get {
                return ResourceManager.GetString("TournamentJsonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing tournament {0}.
        /// </summary>
        internal static string TournamentJsonExceptionTitle {
            get {
                return ResourceManager.GetString("TournamentJsonExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load tournament.
        /// </summary>
        internal static string TournamentLoadButton {
            get {
                return ResourceManager.GetString("TournamentLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Tap &apos;Load tournament&apos;..
        /// </summary>
        internal static string TournamentLoadLabel {
            get {
                return ResourceManager.GetString("TournamentLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament has no name.
        /// </summary>
        internal static string TournamentNoName {
            get {
                return ResourceManager.GetString("TournamentNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was found..
        /// </summary>
        internal static string TournamentSelectedLabel {
            get {
                return ResourceManager.GetString("TournamentSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TournamentSelectedTitle {
            get {
                return ResourceManager.GetString("TournamentSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tournament.
        /// </summary>
        internal static string TournamentTitle {
            get {
                return ResourceManager.GetString("TournamentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmonitored.
        /// </summary>
        internal static string UnmonitoredButton {
            get {
                return ResourceManager.GetString("UnmonitoredButton", resourceCulture);
            }
        }
    }
}
